name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1   
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  fluttertoast: 
  provider: ^6.0.5 
  get: ^4.6.5


  cupertino_icons: ^1.0.6
  flutter_slidable:
  google_fonts:
  shimmer: ^3.0.0
  http: ^1.2.2  
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/appicon.png"    

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/cart.gif
    - assets/paypal_logo.png
    - assets/orderplaced.gif
    - assets/cash_on_delivery.png
    - assets/payoneer_logo.png
    - assets/credit_debit_card.png
    - assets/promo-banner/
    - assets/categories/
